type: data
name: Config
label: Site configuration
singleInstance: true
readOnly: true
fields:
  - type: image
    name: favicon
    label: Favicon
    default: ''
  - type: model
    name: header
    label: Header configuration
    models: [Header]
  - type: model
    name: footer
    label: Footer configuration
    models: [Footer]
